---
controller_templates:
  - name: Kubernetes / Namespace / Create
    description: Ensures a namespace exists on a Kubernetes cluster
    project: Containers
    inventory: Localhost
    playbook: playbooks/kubernetes/namespaces.yml
    concurrent_jobs_enabled: true
    ask_credential_on_launch: true
    execution_environment: CUSTOM / Containers
    survey_spec:
      name: Namespace Parameters
      description: Namespace parameters
      spec:
        - question_name: Namespace Name
          required: true
          variable: namespace_present_name
          type: text
          min: 1
          max: 128
        - question_name: Namespace Labels
          required: false
          variable: namespace_present_labels
          type: textarea
          min: 0
          max: 512
