---
controller_credential_types:
  - name: Kubeconfig
    description: Credential for Kubeconfig files
    inputs:
      fields:
        - id: kubeconfig
          type: string
          label: Kubeconfig contents
          secret: true
          multiline: true
      required:
        - kubeconfig
    injectors:
      env:
        K8S_AUTH_KUBECONFIG: !unsafe "{{ tower.filename.kubeconfig }}"
      file:
        template.kubeconfig: !unsafe "{{ kubeconfig }}"
